name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Get short SHA
        id: get_short_sha
        run: echo "short_sha=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_OUTPUT
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: sisman/my-app:${{ steps.get_short_sha.outputs.short_sha }}
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "$DEPLOYMENT_SSH_KEY" | base64 -d > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Update deployment repository
        run: |
          git clone https://github.com/omersisman/argocd-app-config.git
          cd argocd-app-config/dev
      
          # Update the dev/deployment.yaml file with the new Docker image tag
          sed -i 's|image: sisman/my-app:.*$|image: sisman/my-app:${{ steps.get_short_sha.outputs.short_sha }}|' deployment.yaml

          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"

          git remote set-url origin "https://${{ secrets.DEPLOYMENT_SSH_KEY }}@github.com/omersisman/argocd-app-config.git"
          
          git commit -am "Update Docker image tag in deployment.yaml"
          git push origin main


